"""Write generated Google Assistant entity config YAML."""

from __future__ import annotations

import os
from typing import Any

import yaml
from homeassistant.core import HomeAssistant

from .const import OUTPUT_FILENAME

HEADER = (
    "# Auto-generated by google_assistant_manager integration.\n"
    "# Do not edit manually - use the Google Assistant panel in Home Assistant.\n\n"
)


async def write_config(hass: HomeAssistant, store_data: dict[str, Any]) -> None:
    """Render store data into google_assistant_entity_config.yaml."""
    output_path = os.path.join(hass.config.config_dir, OUTPUT_FILENAME)
    entities = store_data.get("entities", {})

    config: dict[str, dict[str, Any]] = {}
    for entity_id, cfg in entities.items():
        entry: dict[str, Any] = {}
        if not cfg.get("expose", True):
            entry["expose"] = False
        if cfg.get("name"):
            entry["name"] = cfg["name"]
        aliases = cfg.get("aliases")
        if aliases:
            entry["aliases"] = aliases
        if entry:
            config[entity_id] = entry

    body = yaml.safe_dump(config, default_flow_style=False, allow_unicode=True, sort_keys=True)
    content = HEADER + body

    def _write() -> None:
        with open(output_path, "w", encoding="utf-8") as file_handle:
            file_handle.write(content)

    await hass.async_add_executor_job(_write)
